version: '3'
services: 
    mysql:
        image: mysql:5.7
        volumes: 
            - db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks: 
            - user_def_bridge
        
    wordpress:
        image: 
            wordpress:latest
        ports: 
            - 8090:80
        environment: 
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - wordpress:/var/www/html
        networks: 
            - user_def_bridge
networks: 
    user_def_bridge:
volumes: 
    wordpress:
    db_data:

        